import { Show } from '@/interfaces/Show';

export const shows: Show[] = [
  {
    id: 14,
    isPast: true,
    date: '01/06/2024',
    venueName: 'House of Blues',
    city: 'Cleveland',
    beginEnd: '7 pm - 1 am',
    url: 'https://www.houseofblues.com/cleveland/concert-events',
  },
  {
    id: 15,
    isPast: false,
    date: '03/08/2024',
    venueName: "Sassy's Bar & Grille",
    city: 'Twinsburg',
    beginEnd: '8 pm - 12 pm',
    url: 'https://www.facebook.com/sassysbarandgrille/',
  },
  {
    id: 16,
    isPast: false,
    date: '03/22/2024',
    venueName: 'Mercury Music Lounge',
    city: 'Lakewood',
    beginEnd: '9 pm - 1 am',
    url: 'https://www.facebook.com/MercuryMusicLounge',
  },
  {
    id: 17,
    isPast: false,
    date: '05/24/2024',
    venueName: 'Mercury Music Lounge',
    city: 'Lakewood',
    beginEnd: '9 pm - 1 am',
    url: 'https://www.facebook.com/MercuryMusicLounge',
  },
  {
    id: 18,
    isPast: false,
    date: '06/14/2024',
    venueName: 'Shooters on the Water',
    city: 'Cleveland',
    beginEnd: '9pm - 1am',
    url: 'https://www.facebook.com/shootersflats/',
  },
  {
    id: 19,
    isPast: false,
    date: '07/13/2024',
    venueName: 'Shooters on the Water',
    city: 'Cleveland',
    beginEnd: '9pm - 1am',
    url: 'https://www.facebook.com/shootersflats/',
  },
  {
    id: 191,
    isPast: false,
    date: '08/14/2024',
    venueName: 'The Round House Bar',
    city: 'Put-in-Bay',
    beginEnd: '9 pm - 12 am',
    url: 'https://www.theroundhousebar.com/',
  },
  {
    id: 192,
    isPast: false,
    date: '08/15/2024',
    venueName: 'The Round House Bar',
    city: 'Put-in-Bay',
    beginEnd: '9 pm - 12 am',
    url: 'https://www.theroundhousebar.com/',
  },
  {
    id: 20,
    isPast: false,
    date: '09/06/2024',
    venueName: 'Shooters on the Water',
    city: 'Cleveland',
    beginEnd: '9pm - 1am',
    url: 'https://www.facebook.com/shootersflats/',
  },
  {
    id: 21,
    isPast: false,
    date: '09/13/2024',
    venueName: 'Mercury Music Lounge',
    city: 'Lakewood',
    beginEnd: '9 pm - 1 am',
    url: 'https://www.facebook.com/MercuryMusicLounge',
  },
  {
    id: 22,
    isPast: false,
    date: '09/20/2024',
    venueName: 'Oktoberfest',
    city: 'Cuyahoga Falls',
    beginEnd: '1 pm - 4 pm',
    url: 'https://oktoberfestcfo.com/',
  },
  {
    id: 23,
    isPast: false,
    date: '11/23/2024',
    venueName: 'Mercury Music Lounge',
    city: 'Lakewood',
    beginEnd: '9 pm - 1 am',
    url: 'https://www.facebook.com/MercuryMusicLounge',
  },
];
