import { Show } from '@/interfaces/Show';

export const shows: Show[] = [
  // {
  //   id: 1,
  //   isPast: true,
  //   date: '03/03/2023',
  //   venueName: "Sassy's Bar & Grille",
  //   city: 'Twinsburg',
  //   beginEnd: '9 pm - 12 pm',
  //   url: 'https://www.facebook.com/sassysbarandgrille/',
  // },
  // {
  //   id: 2,
  //   isPast: true,
  //   date: '03/17/2023',
  //   venueName: 'Grindstone Tap House',
  //   city: 'Berea (St. Paddy’s Day 🍀)',
  //   beginEnd: '5 pm - 8 pm',
  //   url: 'https://www.facebook.com/GrindstoneTaps',
  // },

  // {
  //   id: 3,
  //   isPast: true,
  //   date: '05/13/2023',
  //   venueName: 'Grindstone Tap House',
  //   city: 'Berea',
  //   beginEnd: '8 pm - 11 pm',
  //   url: 'https://www.facebook.com/GrindstoneTaps',
  // },

  // {
  //   id: 4,
  //   isPast: true,
  //   date: '06/03/2023',
  //   venueName: 'The Round House Bar',
  //   city: 'Put-in-Bay',
  //   beginEnd: '2 pm - 5:30 pm',
  //   url: 'https://www.theroundhousebar.com/',
  // },

  // {
  //   id: 5,
  //   isPast: true,
  //   date: '06/04/2023',
  //   venueName: 'The Round House Bar',
  //   city: 'Put-in-Bay',
  //   beginEnd: '2 pm - 5:30 pm',
  //   url: 'https://www.theroundhousebar.com/',
  // },

  // {
  //   id: 6,
  //   isPast: true,
  //   date: '06/10/2023',
  //   venueName: 'Mercury Music Lounge',
  //   city: 'Lakewood',
  //   beginEnd: '9 pm - 1 am',
  //   url: 'https://www.facebook.com/MercuryMusicLounge',
  // },

  // {
  //   id: 7,
  //   isPast: true,
  //   date: '07/07/2023',
  //   venueName: 'Grindstone Tap House',
  //   city: 'Berea',
  //   beginEnd: '8 pm - 11 pm',
  //   url: 'https://www.facebook.com/GrindstoneTaps',
  // },

  // {
  //   id: 8,
  //   isPast: true,
  //   date: '07/28/2023',
  //   venueName: 'South Euclid Summer Concert Series',
  //   city: 'South Euclid',
  //   beginEnd: '7 pm - 10 pm',
  //   url: 'https://www.facebook.com/EndRockCle/events',
  // },

  // {
  //   id: 9,
  //   isPast: true,
  //   date: '08/03/2023',
  //   venueName: 'The Round House Bar',
  //   city: 'Put-in-Bay',
  //   beginEnd: '8:30 pm - 12 am',
  //   url: 'https://www.theroundhousebar.com/',
  // },

  // {
  //   id: 91,
  //   isPast: false,
  //   date: '09/02/2023',
  //   venueName: 'Private Event',
  //   city: 'XO',
  //   beginEnd: '?? - ??',
  //   url: 'https://www.facebook.com/EndRockCle',
  // },

  {
    id: 92,
    isPast: true,
    date: '09/09/2023',
    venueName: 'Shooters on the Water',
    city: 'Cleveland',
    beginEnd: '5pm - 9pm',
    url: 'https://www.facebook.com/shootersflats/',
  },

  {
    id: 10,
    isPast: true,
    date: '09/17/2023',
    venueName: 'Oktoberfest',
    city: 'Cuyahoga Falls',
    beginEnd: '1 pm - 4 pm',
    url: 'https://www.theroundhousebar.com/',
  },

  {
    id: 11,
    isPast: true,
    date: '10/14/2023',
    venueName: 'The Workz',
    city: 'Cuyahoga Falls',
    beginEnd: '8 pm - 11 pm',
    url: 'https://www.facebook.com/playattheworkz/about',
  },
  {
    id: 12,
    isPast: false,
    date: '11/22/2023',
    venueName: 'Grindstone Tap House',
    city: 'Berea',
    beginEnd: '7 pm - 10 pm',
    url: 'https://www.facebook.com/GrindstoneTaps',
  },
  {
    id: 13,
    isPast: false,
    date: '12/02/2023',
    venueName: 'Mercury Music Lounge',
    city: 'Lakewood',
    beginEnd: '9 pm - 1 am',
    url: 'https://www.facebook.com/MercuryMusicLounge',
  },
  {
    id: 14,
    isPast: false,
    date: '01/06/2024',
    venueName: 'House of Blues',
    city: 'Cleveland',
    beginEnd: '7 pm - 1 am',
    url: 'https://www.houseofblues.com/cleveland/concert-events',
  },
  {
    id: 15,
    isPast: false,
    date: '03/08/2024',
    venueName: "Sassy's Bar & Grille",
    city: 'Twinsburg',
    beginEnd: '8 pm - 12 pm',
    url: 'https://www.facebook.com/sassysbarandgrille/',
  },
];
