export const songList = [
  { artist: '311', song: 'Down' },
  { artist: 'Alice in Chains', song: 'Man in the Box' },
  { artist: 'Beastie Boys', song: 'Sabotage' },
  { artist: 'Better Than Ezra', song: 'Good' },
  { artist: 'Blink-182', song: 'All the Small Things' },
  { artist: 'Blink-182', song: 'Dammit' },
  { artist: 'Blink-182', song: "What's My Age Again?" },
  { artist: 'Blur', song: 'Song 2' },
  { artist: 'Bryan Adams', song: "Summer of '69" },
  { artist: 'Bush', song: 'Glycerine' },
  { artist: 'Bush', song: 'Machinehead' },
  { artist: 'Cake', song: 'Short Skirt / Long Jacket' },
  { artist: 'Chumbawamba', song: 'Tubthumping' },
  { artist: 'Collective Soul', song: 'Shine' },
  { artist: 'Eve 6', song: 'Inside Out' },
  { artist: 'Everclear', song: 'Santa Monica' },
  { artist: 'Fall Out Boy', song: "Sugar, We're Going Down" },
  { artist: 'Foo Fighters', song: 'Everlong' },
  { artist: 'Fountains of Wayne', song: "Stacy's Mom" },
  { artist: 'Franz Ferdinand', song: 'Take Me Out' },
  { artist: 'Gin Blossoms', song: 'Hey Jealousy' },
  { artist: 'Goo Goo Dolls', song: 'Slide' },
  { artist: 'Green Day', song: 'Basket Case' },
  { artist: 'Green Day', song: 'Good Riddance (Time of Your Life)' },
  { artist: 'Green Day', song: 'When I Come Around' },
  { artist: 'Harvey Danger', song: 'Flagpole Sitta' },
  { artist: 'Hole', song: 'Celebrity Skin' },
  { artist: 'Jimmy Eat World', song: 'The Middle' },
  { artist: 'Kings of Leon', song: 'Use Somebody' },
  { artist: 'Lit', song: 'My Own Worst Enemy' },
  { artist: 'Misfits', song: 'Hybrid Moments' },
  { artist: 'Nirvana', song: 'Smells Like Teen Spirit' },
  { artist: 'Pearl Jam', song: 'Alive' },
  { artist: 'Pixies', song: 'Where is My Mind?' },
  { artist: 'Rage Against the Machine', song: 'Killing in the Name' },
  { artist: 'Ramones', song: 'I Wanna Be Sedated' },
  { artist: 'Red Hot Chili Peppers', song: 'Under the Bridge' },
  { artist: 'Semisonic', song: 'Closing Time' },
  { artist: 'Smash Mouth', song: 'All Star' },
  { artist: 'Stone Temple Pilots', song: 'Plush' },
  { artist: 'Sublime', song: 'Santeria' },
  { artist: 'Sublime', song: 'What I Got' },
  { artist: 'Sum 41', song: 'Fat Lip' },
  { artist: 'The All-American Rejects', song: 'Swing, Swing' },
  { artist: 'The Cranberries', song: 'Zombie' },
  { artist: 'The Darkness', song: 'I Believe in a Thing Called Love' },
  { artist: 'The Killers', song: 'Mr. Brightside' },
  { artist: 'The Offspring', song: 'Come Out and Play' },
  {
    artist: 'The Presidents of the United States of America',
    song: 'Cleveland Rocks',
  },
  { artist: 'The Smashing Pumpkins', song: 'Today' },
  { artist: 'The Strokes', song: 'Last Nite' },
  { artist: 'The White Stripes', song: 'Seven Nation Army' },
  { artist: 'Third Eye Blind', song: 'Semi-Charmed Life' },
  { artist: 'Tom Petty and the Heartbreakers', song: 'American Girl' },
  { artist: 'Weezer', song: 'Buddy Holly' },
  { artist: 'Weezer', song: "Say It Ain't So" },
];
