export const songList = [
  { artist: '311', title: 'Down' },
  { artist: 'Alice in Chains', title: 'Man in the Box' },
  { artist: 'Beastie Boys', title: 'Sabotage' },
  { artist: 'Better Than Ezra', title: 'Good' },
  { artist: 'Blink-182', title: 'All the Small Things' },
  { artist: 'Blink-182', title: 'Dammit' },
  { artist: 'Blink-182', title: "What's My Age Again?" },
  { artist: 'Blur', title: 'Song 2' },
  { artist: 'Bryan Adams', title: "Summer of '69" },
  { artist: 'Bush', title: 'Glycerine' },
  { artist: 'Bush', title: 'Machinehead' },
  { artist: 'Cake', title: 'Short Skirt / Long Jacket' },
  { artist: 'Chumbawamba', title: 'Tubthumping' },
  { artist: 'Collective Soul', title: 'Shine' },
  { artist: 'Eve 6', title: 'Inside Out' },
  { artist: 'Everclear', title: 'Santa Monica' },
  { artist: 'Fall Out Boy', title: "Sugar, We're Going Down" },
  { artist: 'Foo Fighters', title: 'Everlong' },
  { artist: 'Fountains of Wayne', title: "Stacy's Mom" },
  { artist: 'Franz Ferdinand', title: 'Take Me Out' },
  { artist: 'Gin Blossoms', title: 'Hey Jealousy' },
  { artist: 'Goo Goo Dolls', title: 'Slide' },
  { artist: 'Green Day', title: 'Basket Case' },
  { artist: 'Green Day', title: 'Good Riddance (Time of Your Life)' },
  { artist: 'Green Day', title: 'When I Come Around' },
  { artist: 'Harvey Danger', title: 'Flagpole Sitta' },
  { artist: 'Hole', title: 'Celebrity Skin' },
  { artist: 'Jimmy Eat World', title: 'The Middle' },
  { artist: 'Kings of Leon', title: 'Use Somebody' },
  { artist: 'Lit', title: 'My Own Worst Enemy' },
  { artist: 'Misfits', title: 'Hybrid Moments' },
  { artist: 'Nirvana', title: 'Smells Like Teen Spirit' },
  { artist: 'Pearl Jam', title: 'Alive' },
  { artist: 'Pixies', title: 'Where is My Mind?' },
  { artist: 'Rage Against the Machine', title: 'Killing in the Name' },
  { artist: 'Ramones', title: 'I Wanna Be Sedated' },
  { artist: 'Red Hot Chili Peppers', title: 'Under the Bridge' },
  { artist: 'Semisonic', title: 'Closing Time' },
  { artist: 'Smash Mouth', title: 'All Star' },
  { artist: 'Stone Temple Pilots', title: 'Plush' },
  { artist: 'Sublime', title: 'Santeria' },
  { artist: 'Sublime', title: 'What I Got' },
  { artist: 'Sum 41', title: 'Fat Lip' },
  { artist: 'The All-American Rejects', title: 'Swing, Swing' },
  { artist: 'The Cranberries', title: 'Zombie' },
  { artist: 'The Darkness', title: 'I Believe in a Thing Called Love' },
  { artist: 'The Killers', title: 'Mr. Brightside' },
  { artist: 'The Offspring', title: 'Come Out and Play' },
  {
    artist: 'The Presidents of the United States of America',
    title: 'Cleveland Rocks',
  },
  { artist: 'The Smashing Pumpkins', title: 'Today' },
  { artist: 'The Strokes', title: 'Last Nite' },
  { artist: 'The White Stripes', title: 'Seven Nation Army' },
  { artist: 'Third Eye Blind', title: 'Semi-Charmed Life' },
  { artist: 'Tom Petty and the Heartbreakers', title: 'American Girl' },
  { artist: 'Weezer', title: 'Buddy Holly' },
  { artist: 'Weezer', title: "Say It Ain't So" },
];
