export const songList = [
    { song: 'All Star', artist: 'Smashmouth' },
    { song: 'All the Small Things', artist: 'Blink 182' },
    { song: 'American Girl', artist: 'Tom Petty' },
    { song: 'Basket Case', artist: 'Green Day' },
    { song: 'Buddy Holly', artist: 'Weezer' },
    { song: 'Cleveland Rocks', artist: 'POTUS' },
    { song: 'Dammit', artist: 'Blink 182' },
    { song: 'Everlong', artist: 'Foo Fighters' },
    { song: 'Flagpole Sita', artist: 'Harvy Danger' },
    { song: 'Good', artist: 'Better than Ezra' },
    { song: 'Hey Jealousy', artist: 'Gin Blossoms' },
    { song: 'Machine Head', artist: 'Bush' },
    { song: 'Mr. Brightside', artist: 'The Killers' },
    { song: 'My Own Worst Enemy', artist: 'Lit' },
    { song: 'Sabotage', artist: 'Beasty Boys' },
    { song: 'Santeria', artist: 'Sublime' },
    { song: 'Say It Aint So', artist: 'Weezer' },
    { song: 'Semi Charmed Life', artist: 'Third Eye Blind' },
    { song: 'Shine', artist: 'Collective Soul' },
    { song: 'Slide', artist: 'Goo Goo Dolls' },
    { song: 'Smells Like Teen Spirit', artist: 'Nirvana' },
    { song: 'Song 2', artist: 'Blur' },
    { song: "Sugar, We're Going Down", artist: 'Fallout Boy' },
    { song: 'Summer of 69 (nice)', artist: 'Bryan Adams' },
    { song: 'Swing Swing', artist: 'All American Rejects' },
    { song: 'The Middle', artist: 'Jimmy Eat World' },
    { song: 'Today', artist: 'Smashing Pumpkins' },
    { song: 'Under the Bridge', artist: 'RHCP' },
    { song: "What's My Age Again", artist: 'Blink 182' },
    { song: 'Where is My Mind', artist: 'The Pixies' },
    { song: 'Zombie', artist: 'The Cranberries' },
    { song: 'And so on...', artist: 'And so forth...' },
];
