export const songList = [
    { song: "Sugar, We're Going Down", artist: 'Fallout Boy' },
    { song: "What's My Age Again", artist: 'Blink 182' },
    { song: 'Alive', artist: 'Pearl Jam' },
    { song: 'All Star', artist: 'Smashmouth' },
    { song: 'All the Small Things', artist: 'Blink 182' },
    { song: 'American Girl', artist: 'Tom Petty' },
    { song: 'And so on...', artist: 'and so forth...' },
    { song: 'Basket Case', artist: 'Green Day' },
    { song: 'Buddy Holly', artist: 'Weezer' },
    { song: 'Cleveland Rocks', artist: 'POTUS' },
    { song: 'Closing Time', artist: 'Semisonic' },
    { song: 'Come Out and Play', artist: 'The Offspring' },
    { song: 'Dammit', artist: 'Blink 182' },
    { song: 'Everlong', artist: 'Foo Fighters' },
    { song: 'Flagpole Sita', artist: 'Harvey Danger' },
    { song: 'Good', artist: 'Better than Ezra' },
    { song: 'Hey Jealousy', artist: 'Gin Blossoms' },
    { song: 'Killing in the Name', artist: 'RATM' },
    { song: 'Machine Head', artist: 'Bush' },
    { song: 'Man in the Box', artist: 'Alice in Chains' },
    { song: 'Mr. Brightside', artist: 'The Killers' },
    { song: 'My Own Worst Enemy', artist: 'Lit' },
    { song: 'Plush', artist: 'Stone Temple Pilots' },
    { song: 'Sabotage', artist: 'Beasty Boys' },
    { song: 'Santeria', artist: 'Sublime' },
    { song: "Say It Ain't So", artist: 'Weezer' },
    { song: 'Semi Charmed Life', artist: 'Third Eye Blind' },
    { song: 'Seven Nation Army', artist: 'The White Stripes' },
    { song: 'Shine', artist: 'Collective Soul' },
    { song: 'Slide', artist: 'Goo Goo Dolls' },
    { song: 'Smells Like Teen Spirit', artist: 'Nirvana' },
    { song: 'Song 2', artist: 'Blur' },
    { song: "Stacy's Mom", artist: 'Fountains of Wayne' },
    { song: 'Summer of 69', artist: 'Bryan Adams' },
    { song: 'Swing Swing', artist: 'All American Rejects' },
    { song: 'The Middle', artist: 'Jimmy Eat World' },
    { song: 'Today', artist: 'Smashing Pumpkins' },
    { song: 'Tubthumping', artist: 'Chumbawumba' },
    { song: 'Under the Bridge', artist: 'RHCP' },
    { song: 'When I Come Around', artist: 'Green Day' },
    { song: 'Where is My Mind', artist: 'The Pixies' },
    { song: 'Zombie', artist: 'The Cranberries' },
    { song: 'And so on...', artist: 'and so forth...' },
];
